["!local"]
rockTexture = "minecraft:block/stone"

[":bauxite_ore"]
oreTexture = ":block/bauxite_ore"

[":uranium_ore"]
oreTexture = ":block/uranium_ore"

[":zinc_ore"]
oreTexture = ":block/zinc_ore"

[":bismuth_ore"]
oreTexture = ":block/bismuth_ore"

[":platinum_ore"]
oreTexture = ":block/platinum_ore"
