["!local"]
rockTexture = "minecraft:block/stone"

[":copper_ore"]
oreTexture = ":block/copper_ore"

[":bauxite_ore"]
oreTexture = ":block/bauxite_ore"

[":tin_ore"]
oreTexture = ":block/tin_ore"

[":silver_ore"]
oreTexture = ":block/silver_ore"

[":lead_ore"]
oreTexture = ":block/lead_ore"

[":nickel_ore"]
oreTexture = ":block/nickel_ore"

[":uranium_ore"]
oreTexture = ":block/uranium_ore"

[":zinc_ore"]
oreTexture = ":block/zinc_ore"

[":bismuth_ore"]
oreTexture = ":block/bismuth_ore"

[":platinum_ore"]
oreTexture = ":block/platinum_ore"

