["!local"]
rockTexture = "minecraft:block/stone"

[":copper_ore"]
oreTexture = ":block/ores/copper_ore"

[":tin_ore"]
oreTexture = ":block/ores/tin_ore"

[":silver_ore"]
oreTexture = ":block/ores/silver_ore"

[":lead_ore"]
oreTexture = ":block/ores/lead_ore"

[":nickel_ore"]
oreTexture = ":block/ores/nickel_ore"

