["!local"]
rockTexture = "minecraft:block/stone"

[":copper_ore"]
oreTexture = ":block/copper_ore"

[":tin_ore"]
oreTexture = ":block/tin_ore"

[":silver_ore"]
oreTexture = ":block/silver_ore"

[":lead_ore"]
oreTexture = ":block/lead_ore"

[":nickel_ore"]
oreTexture = ":block/nickel_ore"
