onEvent('recipes', event => {
  event.remove({id: 'mysticalagriculture:essence/common/constantan_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/invar_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/electrum_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/bronze_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/nickel_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/silver_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/lead_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/tin_ingot'})
  event.remove({id: 'mysticalagriculture:essence/common/copper_ingot'})

  event.remove({id: 'mekanism:processing/uranium/dust/from_ingot'})
  event.remove({id: 'mekanism:processing/uranium/dust/from_ore'})
  event.remove({id: 'mekanism:processing/uranium/dust/from_dirty_dust'})
  event.remove({output: 'mekanism:block_bronze'})
  event.remove({output: 'mekanism:nugget_bronze'})
  event.remove({id: 'mekanism:processing/bronze/ingot/from_block'})
  event.remove({id: 'mekanism:processing/bronze/ingot/from_nuggets'})
  event.remove({id: 'mekanism:processing/bronze/ingot/from_dust_smelting'})
  event.remove({id: 'mekanism:processing/bronze/ingot/from_dust_blasting'})
  event.remove({output: 'mekanism:block_charcoal'})

  event.remove({output: 'thermal:apple_block'})
  event.remove({output: 'thermal:potato_block'})
  event.remove({output: 'thermal:carrot_block'})
  event.remove({output: 'thermal:beetroot_block'})
  event.remove({output: 'thermal:bamboo_block'})
  event.remove({id: 'thermal:enderium_dust_2'})
  event.remove({id: 'thermal:lumium_dust_4'})
  event.remove({id: 'thermal:signalum_dust_4'})
  event.remove({id: 'thermal:constantan_dust_2'})
  event.remove({id: 'thermal:invar_dust_3'})
  event.remove({id: 'thermal:electrum_dust_2'})
  event.remove({id: 'thermal:bronze_dust_4'})
  event.remove({id: 'thermal:fire_charge/signalum_ingot_4'})
  event.remove({id: 'thermal:fire_charge/bronze_ingot_4'})
  event.remove({id: 'thermal:fire_charge/electrum_ingot_2'})
  event.remove({id: 'thermal:fire_charge/enderium_ingot_2'})
  event.remove({id: 'thermal:fire_charge/invar_ingot_3'})
  event.remove({id: 'thermal:fire_charge/constantan_ingot_2'})
  event.remove({id: 'thermal:fire_charge/lumium_ingot_4'})

  event.remove({output: 'cyclic:crafting_stick'})
  event.remove({output: 'cyclic:crafting_bag'})
  event.remove({output: 'cyclic:uncrafter'})

  event.remove({output: 'titanium:gold_gear'})
  event.remove({output: 'titanium:iron_gear'})
  event.remove({output: 'titanium:diamond_gear'})

  event.remove({output: 'quark:charcoal_block'})

  event.remove({output: 'vanillatweaks:charcoalblock'})
});
