events.listen('jei.hide.items', function (event) {
  event.hide('mekanism:upgrade_anchor')
  event.hide('cyclic:uncrafter')

  // Immersive Engineering
  event.hide('immersiveengineering:ore_copper')
  event.hide('immersiveengineering:ingot_copper')
  event.hide('immersiveengineering:dust_copper')
  event.hide('immersiveengineering:nugget_copper')
  event.hide('immersiveengineering:storage_copper')
  event.hide('immersiveengineering:slab_storage_copper')
  event.hide('immersiveengineering:ore_aluminum')
  event.hide('immersiveengineering:ingot_aluminum')
  event.hide('immersiveengineering:dust_aluminum')
  event.hide('immersiveengineering:nugget_aluminum')
  event.hide('immersiveengineering:storage_aluminum')
  event.hide('immersiveengineering:slab_storage_aluminum')
  event.hide('immersiveengineering:ore_lead')
  event.hide('immersiveengineering:ingot_lead')
  event.hide('immersiveengineering:dust_lead')
  event.hide('immersiveengineering:nugget_lead')
  event.hide('immersiveengineering:storage_lead')
  event.hide('immersiveengineering:slab_storage_lead')
  event.hide('immersiveengineering:ore_silver')
  event.hide('immersiveengineering:ingot_silver')
  event.hide('immersiveengineering:dust_silver')
  event.hide('immersiveengineering:nugget_silver')
  event.hide('immersiveengineering:storage_silver')
  event.hide('immersiveengineering:slab_storage_silver')
  event.hide('immersiveengineering:ore_nickel')
  event.hide('immersiveengineering:ingot_nickel')
  event.hide('immersiveengineering:dust_nickel')
  event.hide('immersiveengineering:nugget_nickel')
  event.hide('immersiveengineering:storage_nickel')
  event.hide('immersiveengineering:slab_storage_nickel')
  event.hide('immersiveengineering:ore_uranium')
  event.hide('immersiveengineering:ingot_uranium')
  event.hide('immersiveengineering:dust_uranium')
  event.hide('immersiveengineering:nugget_uranium')
  event.hide('immersiveengineering:storage_uranium')
  event.hide('immersiveengineering:slab_storage_uranium')
  event.hide('immersiveengineering:dust_iron')
  event.hide('immersiveengineering:dust_gold')
  event.hide('immersiveengineering:dust_steel')
  event.hide('immersiveengineering:storage_steel')
  event.hide('immersiveengineering:ingot_steel')
  event.hide('immersiveengineering:nugget_steel')

  // Mekanism
  event.hide('mekanism:copper_ore')
  event.hide('mekanism:block_copper')
  event.hide('mekanism:ingot_copper')
  event.hide('mekanism:dust_copper')
  event.hide('mekanism:nugget_copper')
  event.hide('mekanism:tin_ore')
  event.hide('mekanism:block_tin')
  event.hide('mekanism:ingot_tin')
  event.hide('mekanism:dust_tin')
  event.hide('mekanism:nugget_tin')
  event.hide('mekanism:uranium_ore')
  event.hide('mekanism:block_uranium')
  event.hide('mekanism:ingot_uranium')
  event.hide('mekanism:dust_uranium')
  event.hide('mekanism:nugget_uranium')
  event.hide('mekanism:lead_ore')
  event.hide('mekanism:block_lead')
  event.hide('mekanism:ingot_lead')
  event.hide('mekanism:dust_lead')
  event.hide('mekanism:nugget_lead')
  event.hide('mekanism:dust_iron')
  event.hide('mekanism:dust_gold')
  event.hide('mekanism:block_steel')
  event.hide('mekanism:ingot_steel')
  event.hide('mekanism:nugget_steel')
  event.hide('mekanism:nugget_bronze')
  event.hide('mekanism:dust_bronze')
  event.hide('mekanism:ingot_bronze')
  event.hide('mekanism:block_bronze')

  // Ice And Fire
  event.hide('iceandfire:copper_ore')
  event.hide('iceandfire:copper_block')
  event.hide('iceandfire:copper_ingot')
  event.hide('iceandfire:copper_nugget')
  event.hide('iceandfire:silver_ore')
  event.hide('iceandfire:silver_block')
  event.hide('iceandfire:silver_ingot')
  event.hide('iceandfire:silver_nugget')

  // Silent Gear
  event.hide('silentgear:iron_rod')

  // Silent Gems
  event.hide('silentgems:silver_ore')
  event.hide('silentgems:silver_block')
  event.hide('silentgems:silver_ingot')
  event.hide('silentgems:silver_nugget')

  // Basic Nether Ore
  event.hide('bno:aluminum_block')
  event.hide('bno:copper_block')
  event.hide('bno:lead_block')
  event.hide('bno:nickel_block')
  event.hide('bno:silver_block')
  event.hide('bno:tin_block')
  event.hide('bno:osmium_block')
  event.hide('bno:uranium_block')
  event.hide('bno:aluminum_ingot')
  event.hide('bno:copper_ingot')
  event.hide('bno:lead_ingot')
  event.hide('bno:nickel_ingot')
  event.hide('bno:silver_ingot')
  event.hide('bno:tin_ingot')
  event.hide('bno:osmium_ingot')
  event.hide('bno:uranium_ingot')
  event.hide('bno:aluminum_nugget')
  event.hide('bno:copper_nugget')
  event.hide('bno:lead_nugget')
  event.hide('bno:nickel_nugget')
  event.hide('bno:silver_nugget')
  event.hide('bno:tin_nugget')
  event.hide('bno:osmium_nugget')

  // Applied Energistics 2
  event.hide('appliedenergistics2:gold_dust')
  event.hide('appliedenergistics2:iron_dust')

  // Create
  event.hide('create:copper_ingot')
  event.hide('create:copper_ore')
  event.hide('create:copper_block')
  event.hide('create:copper_nugget')
})
