
[working-duration-multiplier]
	#The default duration multiplied with this will be the used working duration.
	#Range: 1 ~ 25
	alfheim-market = 1
	#Range: 1 ~ 5000
	industrial-agglomeration-factory = 1
	#Range: > 1
	mechanical-mana-pool = 1
	#Range: 1 ~ 100
	mechanical-runic-altar = 1
	#Range: > 1
	mechanical-daisy = 3
	#Range: 1 ~ 50
	mechanical-brewery = 1
	#Range: > 1
	mechanical-apothecary = 1

[alfheim-market]
	#The amount of mana used in alfheim market to trade items [Default: 500]
	#Range: > 1
	recipe-cost = 500

[max-mana-capacity]
	#The default amount of mana capacity in each machine.
	#Range: > 1
	alfheim-market = 100000
	#Range: > 500000
	industrial-agglomeration-factory = 1000000
	#Range: > 1
	mechanical-mana-pool = 100000
	#Range: > 1
	mechanical-runic-altar = 250000
	#Range: > 1
	mechanical-brewery = 100000
	#Range: > 1
	mana-battery = 10000000

