
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "505000ff"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "5028007f"
	#The color for the background of the tooltip.
	background = "f0100010"

