
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "FF2bc7d9"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "FF2bc7d9"
	#The color for the background of the tooltip.
	background = "CC232323"

