
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "FFC0C0C0"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "FFC0C0C0"
	#The color for the background of the tooltip.
	background = "CC2F80C1"

