
#lots of cosmetic stuff in here
[visuals]
	#How much the dummy swings in degrees with respect to the damage dealt. default=0.75
	#Range: 0.0 ~ 2.0
	animationIntensity = 0.75
	#Show hearths instead of damage dealt? (1 hearth = two damage)
	showHearths = false
	#Does dps message update dynamically or will it only appear after each parse? 
	dynamicDPS = true
	#Skin used by the dummy
	#Allowed Values: DEFAULT, ORIGINAL, DUNGEONS, ALTERNATIVE
	texture = "DEFAULT"

	[visuals.damage_number_colors]
		#hex color for various damage sources
		genetic = "0xffffff"
		crit = "0xff0000"
		dragon_breath = "0xFF00FF"
		wither = "0x666666"
		explosion = "0xFFCC33"
		magic = "0x3399FF"
		trident = "0x00FFCC"
		fire = "0xFF9900"
		lightning = "0xFFFF00"
		cactus = "0x006600"
		magic_indirect = "844ce7"
		true_damage = "910038"

