#Requires restart. Ram usage (in MB) = (x * 16 * 2) ^ 3 / 4
#Range: 1 ~ 32
cacheSize = 12
#No comment
debug = false
#Disable all changes from this mod.
enabled = true
#Skip rendering of entities that are not visible (hidden behind blocks). Bosses will be rendered normally. This might cause issues where an entity is partly behind a block and thus does not get rendered but it's usually not really noticable.
skipHiddenEntityRendering = true
#Entities with a width or height greater than this value will always get rendered.
#Range: 0.0 ~ 128.0
skipHiddenEntityRenderingSize = 3.0
#Entities which will always be rendered. (Format: 'modid:entity_name')
skipHiddenEntityRenderingBlacklist = []
#Skip rendering of entities that are not visible (hidden behind blocks). This might cause issues where a tile entity is partly behind a block and thus does not get rendered but it's usually not really noticable.
skipHiddenTileEntityRendering = true
#Tile entities with a width or height greater than this value will always get rendered.
#Range: 0.0 ~ 128.0
skipHiddenTileEntityRenderingSize = 3.0
#Tile entities which will always be rendered. (Format: 'modid:tile_entity_name')
skipHiddenTileEntityRenderingBlacklist = []

#No comment
[optifineShaderOptions]
	#No comment
	entityShadowsCulling = true
	#No comment
	entityShadowsCullingLessAggressiveMode = false
	#No comment
	#Range: 0.0 ~ 128.0
	entityShadowsCullingLessAggressiveModeDiff = 4.0
	#No comment
	entityShadowsDisabled = false
	#No comment
	entityShadowsDistanceLimited = false
	#No comment
	#Range: 0.0 ~ 1024.0
	entityShadowsMaxDistance = 64.0
	#No comment
	terrainShadowsDisabled = false
	#No comment
	terrainShadowsDistanceLimited = false
	#No comment
	#Range: 0.0 ~ 1024.0
	terrainShadowsMaxHorizontalDistance = 128.0
	#No comment
	#Range: 0.0 ~ 1024.0
	terrainShadowsMaxVerticalDistance = 64.0
	#No comment
	tileEntityShadowsCulling = true
	#No comment
	tileEntityShadowsCullingLessAggressiveMode = false
	#No comment
	#Range: 0.0 ~ 128.0
	tileEntityShadowsCullingLessAggressiveModeDiff = 4.0
	#No comment
	tileEntityShadowsDisabled = false
	#No comment
	tileEntityShadowsDistanceLimited = false
	#No comment
	#Range: 0.0 ~ 1024.0
	tileEntityShadowsMaxDistance = 64.0

